In [7]:
import numpy as np

## Creating Numpy Arrays from Python Lists

In [9]:
np.array([1,2,3,4,5,10])

array([ 1,  2,  3,  4,  5, 10])

In [11]:
[3.14,4,2,3]

[3.14, 4, 2, 3]

In [13]:
np.array([1,2,3,4],dtype = "float32")

array([1., 2., 3., 4.], dtype=float32)

In [15]:
a1 = np.array([1,2,3,4])

In [17]:
type(a1)

numpy.ndarray

In [23]:
a2 = np.array([[1,2,3],[3,4,5]])

In [25]:
type(a2)

numpy.ndarray

In [27]:
a2.shape

(2, 3)

In [31]:
a2.dtype

dtype('int32')

In [33]:
a2.size

6

## Creating Numpy Arrays from Scratch
#  zeros, ones, full, arange, linspace


In [39]:
np.zeros([2,4],dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [41]:
np.ones([3,5],dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, sequence by 2
# (this is similar to the built-in range() function)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
np.full([3,5],6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [55]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

### `random`

In [69]:
# Seed for reproducibility
np.random.seed(0)
np.random.random((4,3))

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492]])

In [77]:
np.random.rand(4,4)

array([[0.03842543, 0.63427406, 0.95894927, 0.65279032],
       [0.63505887, 0.99529957, 0.58185033, 0.41436859],
       [0.4746975 , 0.6235101 , 0.33800761, 0.67475232],
       [0.31720174, 0.77834548, 0.94957105, 0.66252687]])

In [73]:
np.random.normal(0,1,(3,3))

array([[ 0.3130677 , -0.85409574, -2.55298982],
       [ 0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852]])

In [75]:
np.random.randint(0,10,[4,5])

array([[6, 8, 4, 1, 4],
       [9, 8, 1, 1, 7],
       [9, 9, 3, 6, 7],
       [2, 0, 3, 5, 9]])

## Array indexing & Slicing
### One-dimensional subarray

In [81]:
x1 = np.random.randint(20,size = 6)

In [83]:
x1

array([ 0, 17, 18,  4,  2, 16])

In [85]:
x1[4],x1[0],x1[-1]

(2, 0, 16)

### Multi - dimensinal array


In [90]:
x2 = np.random.randint(10,size = (3,4))

In [92]:
x2

array([[3, 2, 0, 7],
       [5, 9, 0, 2],
       [7, 2, 9, 2]])

In [94]:
x2[1,2]

0

In [98]:
x2[1,2] = 6

In [100]:
x2

array([[3, 2, 0, 7],
       [5, 9, 6, 2],
       [7, 2, 9, 2]])

#### Slicing:
### `x[start:stop:step]`

In [103]:
x1

array([ 0, 17, 18,  4,  2, 16])

In [105]:
x1[0:3]

array([ 0, 17, 18])

In [107]:
x1[2:4]

array([18,  4])

In [111]:
# every other element, every 2 step
x1[::2]

array([ 0, 18,  2])

In [113]:
x2


array([[3, 2, 0, 7],
       [5, 9, 6, 2],
       [7, 2, 9, 2]])

In [123]:
# two row, three columns
x2[:2,:3]

array([[3, 2, 0],
       [5, 9, 6]])

In [125]:
x2[:,:2]

array([[3, 2],
       [5, 9],
       [7, 2]])

### Resphaping of Arrays & Transpose

In [130]:
grid = np.arange(1,10)
grid.shape

(9,)

In [132]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
x = np.array([1,2,3])

In [140]:
x.shape

(3,)

In [152]:
x.reshape((1,3)).shape

(1, 3)

In [144]:
x

array([1, 2, 3])

In [146]:
x.T

array([1, 2, 3])

#### Array concatenation and splitting

In [157]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [159]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [183]:
grid = np.array([[1,2,3],[4,5,6]])

In [191]:
np.concatenate((grid,grid),axis = 1) # axis = 0 by default

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [193]:
# vstack
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])

In [195]:
np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [197]:
# horizontally stack the arrays:hstack
y = np.array([[99],[99]])
np.hstack((y,grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

### Splitting of arrays

In [200]:
x = np.array([1,2,3,99,69,3,2,1])

In [204]:
x1,x2,x3 = np.split(x,[3,5])

In [208]:
list(x1)

[1, 2, 3]

### Broadcasting and Vectorized operations

In [211]:
a = np.arange(3)

In [213]:
a

array([0, 1, 2])

In [215]:
a + 5 #8 roadcasting

array([5, 6, 7])

In [217]:
b = np.ones((3,3))

In [219]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [221]:
a.shape,b.shape

((3,), (3, 3))

In [223]:
a +b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [225]:
a*b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [227]:
c = np.arange(3).reshape((3,1))

In [229]:
c

array([[0],
       [1],
       [2]])

In [231]:
a + c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Manipulating & Comparing Arrays 
#### Aggeration

In [235]:
list_number = [1,2,3]

In [243]:
ll = np.array(list_number)

In [245]:
ll

array([1, 2, 3])

In [247]:
sum(ll) #Python sum()

6

In [249]:
np.sum(ll) # NumPy sum()

6

In [253]:
# Create a massive Numpy Array

massive_array = np.random.random(10000)
massive_array[:5]
massive_array.shape

(10000,)

In [257]:
%timeit sum(massive_array) # Python built-int function sum()
%timeit np.sum(massive_array) # Numpy's np.sum()

1.31 ms ± 420 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
7.47 μs ± 397 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [259]:
np.mean(massive_array)

0.4972268029420348

In [261]:
np.max(massive_array)

0.9999680225821261

In [263]:
np.min(massive_array)

4.011685566074341e-06

In [265]:
dog_height = [600,470,170,430,300]
dog_height = np.array(dog_height)
np.std(dog_height)

147.32277488562318

### Sorting Arrays
###### np.sort uses an quicksort algorithm

In [272]:
x = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [274]:
#A related function is argsort,which instead returns the indices of the sorted elements:
np.argsort(x)

array([1, 0, 3, 2, 4], dtype=int64)

### Sorting along rows or columns

In [277]:
np.random.seed(42)
MatA = np.random.randint(0,10,size = (4,6))

In [279]:
MatA


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [281]:
np.sort(MatA,axis = 0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [283]:
np.sort(MatA,axis = 1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

#### Linear Algebra

In [286]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [290]:
B = np.array([[6,5],[4,3],[2,1]])

In [294]:
#A (3,3) dot product B (3,2)

In [296]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [298]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [300]:
# B (3x2) dot A (3x3)
B.T #(2x3) dot A (3x3)

array([[6, 4, 2],
       [5, 3, 1]])

In [302]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

#### Dot Product Example


In [307]:
# Number of jars solid
np.random.seed(0)
sales_amounts = np.random.randint(0,20,size = (5,3))

In [309]:
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [313]:
# create weekly_sales DataFrame
import pandas as pd

weekly_sales = pd.DataFrame(sales_amounts,index = ["Mon","Tues","Wed","Thurs","Fri"],columns = ["Almond Butter","Peanut Butter","Cashew Butter"])

In [315]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [317]:
# Create a price array

prices = np.array([10,8,12])

In [321]:
butter_prices = pd.DataFrame(prices.reshape(1,3),index = ["Price"],columns = ["Almond Butter","Peanut Butter","Cashew Butter"] )

In [323]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [339]:
"""
10
8
12
12 15 0
3 3 7

"""
weekly_sales.shape,butter_prices.T.shape

((5, 4), (3, 1))

In [331]:
total_prices = weekly_sales.dot(butter_prices.T)

In [333]:
total_prices

Price
Mon      240
Tues     138
Wed      458
Thurs    232
Fri      142

In [335]:
weekly_sales["Total Price"] = total_prices
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total Price
Mon               12             15              0          240
Tues               3              3              7          138
Wed                9             19             18          458
Thurs              4              6             12          232
Fri                1              6              7          142